Update v1.0.14

diff --git a/.github/workflows/npm-release.yml b/.github/workflows/npm-release.yml
--- a/.github/workflows/npm-release.yml
+++ b/.github/workflows/npm-release.yml
@@ -5,7 +5,7 @@ on:
     branches: [ main ]
     
 jobs:
-  build:
+  Build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -45,7 +45,7 @@ jobs:
           
   RemoveOldRelease:
     runs-on: ubuntu-latest
-    needs: build
+    needs: Build
     steps:
       - name: install github-cli
         run: |
@@ -57,13 +57,44 @@ jobs:
           && sudo apt install gh -y
 
       - name: CheckOut
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Set APP_VERSION env
         run: |
-          sudo chmod a+x git_push.sh \
-          && pre_del_tag=$(./git_push.sh -get_pre_del_tag_name) \
-          && echo APP_OLD_VERSION=v${pre_del_tag} >> ${GITHUB_ENV}
+          APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) \
+
+          function get_pre_del_tag {
+              local v_str=$1
+              baseStr=$(echo $v_str | cut -d'.' -f1)
+              base=${baseStr//v/}
+              major=$(echo $v_str | cut -d'.' -f2)
+              minor=$(echo $v_str | cut -d'.' -f3)
+
+              if ((minor>0)); then
+                  minor=$((minor-1))
+              else
+                  minor=999
+                  if ((major>0)); then
+                      major=$((major-1))
+                  else
+                      major=999
+                      if ((base>0)); then
+                          base=$((base-1))
+                      else
+                          echo "Error: Version cannot be decremented."
+                          exit 1
+                      fi
+                  fi
+              fi
+
+              pre_v_no="v${base}.${major}.${minor}"
+              echo $pre_v_no
+          }
+
+          APP_OLD_VERSION=$(get_pre_del_tag $(get_pre_del_tag $APP_VERSION))
+
+          echo "Old version to remove: ${APP_OLD_VERSION}"
+          echo APP_OLD_VERSION=${APP_OLD_VERSION} >> ${GITHUB_ENV}
 
       - name: Remove Old Release
         run: |
